from analysis_step_1.train_step_1 import train as train_step_1
from analysis_step_1.calculation_duration_step_1 import calculation_duration as calculation_duration_step_1
from analysis_step_1.plot_N_calc import plot_N_calc as step_1_plot_N_calc
from analysis_step_1.plot_k_calc import plot_k_calc as step_1_plot_k_calc
from analysis_step_1.plot_N_success import plot_N_success as step_1_plot_N_success
from analysis_step_1.plot_k_success import plot_k_success as step_1_plot_k_success
from analysis_step_2.train_cycles import train_cycles
from analysis_step_2.train_step_2 import train as train_step_2
from analysis_step_2.calculation_duration_step_2 import calculation_duration as calculation_duration_step_2
from analysis_step_2.plot_a_performance import plot_a_performance
from analysis_step_2.plot_n_performance import plot_n_performance
from analysis_step_2.plot_k_performance import plot_k_performance
from analysis_step_2.plot_k_success import plot_k_success
from analysis_step_2.plot_s_calc import plot_s_calc
from analysis_step_2.plot_k_calc import plot_k_calc
from analysis_step_2.plot_s_performance import plot_s_performance

plot_k_success()
