[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "frenetic_steering"
version = "1.0.0"
dependencies = [
    "numpy",
    "matplotlib",
    "pandas"
]