[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "frenetic_steering"
version = "1.0.0"
dependencies = [
    "matplotlib == 3.8.0",
    "pandas == 2.1.1"
]